#!/usr/bin/env python3

import sys

from lexer import tokenize # lexer
from parser import Parser # parser
from interpreter import Interpreter

def run(code): 
    tokens = tokenize(code)
    parser = Parser(tokens)
    ast = parser.parse()
    interpreter = Interpreter()
    interpreter.eval(ast)

if __name__ == '__main__':
    
    if len(sys.argv) == 1:
        while True :
            line = input("vsil--> ")
            if line.strip() == "exit":
                sys.exit(1)
            run(line)


    if len(sys.argv) > 2:
        print("Too many Arguments!!!")
        print("Usage : vsil <filename.vsil>")
        sys.exit(1)

    filename = sys.argv[1]
    with open(filename, 'r') as f:
        source_code = f.read()

    run(source_code)

